### ISSUE TITLE
[UMBRELLA] Add `hack/update-*.sh`

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#232]
### What would you like to be added?

- [x] #226
- [ ] update-ends-newline.sh #243
- [x] update-go-format.sh #241
- [x] update-go-mod.sh #242

### Why is this needed?

Optimize the development experience
